/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'History' : IDL.Null,
  'Nature' : IDL.Null,
  'MindBlowing' : IDL.Null,
  'Science' : IDL.Null,
});
export const Fact = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'category' : Category,
});

export const idlService = IDL.Service({
  'addFact' : IDL.Func([IDL.Text, Category], [Fact], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllFacts' : IDL.Func([IDL.Opt(Category)], [IDL.Vec(Fact)], ['query']),
  'getFact' : IDL.Func([IDL.Nat], [Fact], ['query']),
  'getRandomFact' : IDL.Func([IDL.Opt(Category)], [Fact], []),
  'initialize' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'History' : IDL.Null,
    'Nature' : IDL.Null,
    'MindBlowing' : IDL.Null,
    'Science' : IDL.Null,
  });
  const Fact = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'category' : Category,
  });
  
  return IDL.Service({
    'addFact' : IDL.Func([IDL.Text, Category], [Fact], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllFacts' : IDL.Func([IDL.Opt(Category)], [IDL.Vec(Fact)], ['query']),
    'getFact' : IDL.Func([IDL.Nat], [Fact], ['query']),
    'getRandomFact' : IDL.Func([IDL.Opt(Category)], [Fact], []),
    'initialize' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };